# Generated by Django 5.1.7 on 2025-08-31 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_messages', '0002_load_message_templates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playermessage',
            old_name='created',
            new_name='created_at',
        ),
    ]
