# Generated by Django 5.1.7 on 2025-09-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_messages', '0003_rename_created_playermessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermessage',
            name='audience',
            field=models.CharField(choices=[('Group', 'Group'), ('User', 'User')], default='Group', max_length=10),
        ),
    ]
