# Generated by Django 5.1.7 on 2025-10-18 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Golfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golfer_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_amateur', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='GolfTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('season_id', models.IntegerField()),
                ('tour_id', models.IntegerField(unique=True)),
                ('tour_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GolfEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourn_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('purse', models.BigIntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('week_number', models.IntegerField(blank=True, null=True)),
                ('playing_format', models.CharField(blank=True, max_length=25)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('current_round', models.IntegerField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golftour')),
            ],
        ),
        migrations.CreateModel(
            name='GolferScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('thru', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=10)),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfevent')),
            ],
            options={
                'unique_together': {('golfer', 'event', 'round')},
            },
        ),
        migrations.CreateModel(
            name='EventEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50)),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfevent')),
            ],
            options={
                'unique_together': {('event', 'golfer')},
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_rank', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfevent')),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event', 'selection_rank')},
            },
        ),
        migrations.CreateModel(
            name='UserPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfevent')),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event', 'golfer')},
            },
        ),
    ]
