# Generated by Django 5.1.7 on 2025-07-17 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Golfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golfer_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='GolfEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GolfTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField()),
                ('season_id', models.IntegerField()),
                ('tour_id', models.IntegerField(unique=True)),
                ('tour_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GolferScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('thru', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=10)),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfevent')),
            ],
        ),
        migrations.CreateModel(
            name='EventEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfevent')),
            ],
        ),
        migrations.AddField(
            model_name='golfevent',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golftour'),
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_rank', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfevent')),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfevent')),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.golfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
