# Generated by Django 5.1.7 on 2025-10-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfer',
            name='world_ranking',
            field=models.IntegerField(default=2999),
        ),
    ]
