# Generated by Django 5.1.7 on 2026-05-16 12:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_golfer_world_ranking'),
        ('groups', '0002_alter_usergroup_access_code_alter_usergroup_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evententry',
            name='made_cut',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='golferscore',
            name='total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evententry',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='golf.golfevent'),
        ),
        migrations.AlterField(
            model_name='evententry',
            name='golfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_entries', to='golf.golfer'),
        ),
        migrations.CreateModel(
            name='GolfGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_fee', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6)),
                ('missed_cut_fine', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6)),
                ('pick_method', models.CharField(choices=[('straight', 'Straight (same order every round)'), ('snake', 'Snake (order reverses each round)')], default='straight', max_length=10)),
                ('picks_per_player', models.PositiveSmallIntegerField(default=5)),
                ('scoring_picks', models.PositiveSmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('open', 'Open for joining'), ('drafting', 'Draft in progress'), ('active', 'Tournament in progress'), ('finished', 'Finished')], default='open', max_length=10)),
                ('rollover_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golf_games_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golf_games', to='golf.golfevent')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golf_games', to='groups.usergroup')),
            ],
            options={
                'unique_together': {('event', 'group')},
            },
        ),
        migrations.CreateModel(
            name='GolfGameEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('draft_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('final_score', models.IntegerField(blank=True, null=True)),
                ('final_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_fines', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_entries', to='golf.golfgame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golf_game_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['draft_position'],
                'unique_together': {('game', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DraftSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('pick_number', models.PositiveSmallIntegerField()),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('auto_assigned', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_slots', to='golf.golfgame')),
                ('game_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_slots', to='golf.golfgameentry')),
            ],
            options={
                'ordering': ['pick_number'],
                'unique_together': {('game', 'round_number', 'game_entry')},
            },
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('auto_assigned', models.BooleanField(default=False)),
                ('picked_at', models.DateTimeField(auto_now_add=True)),
                ('made_cut', models.BooleanField(blank=True, null=True)),
                ('total_strokes', models.IntegerField(blank=True, null=True)),
                ('is_tournament_winner', models.BooleanField(default=False)),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='golf.golfer')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pick', to='golf.draftslot')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='golf.golfgame')),
                ('game_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='golf.golfgameentry')),
            ],
            options={
                'ordering': ['round_number'],
                'unique_together': {('game', 'golfer')},
            },
        ),
        migrations.CreateModel(
            name='GolfGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_rank', models.PositiveSmallIntegerField()),
                ('final_score', models.IntegerField(blank=True, null=True)),
                ('main_pot_won', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('secondary_pot_won', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('fines_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='golf.golfgame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golf_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['final_rank'],
                'unique_together': {('game', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RolloverPot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='golf_rollover', to='groups.usergroup')),
                ('last_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollover_updates', to='golf.golfevent')),
            ],
        ),
        migrations.DeleteModel(
            name='UserPick',
        ),
    ]
