# Generated by Django 5.1.7 on 2026-05-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_evententry_made_cut_golferscore_total_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftslot',
            name='closes_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draftslot',
            name='opens_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
