# Generated by Django 5.1.7 on 2026-05-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_alter_draftslot_closes_at_alter_draftslot_opens_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='golferscore',
            name='round_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
