# Generated by Django 5.1.7 on 2026-05-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0005_golferscore_round_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golferscore',
            name='thru',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
