# Generated by Django 5.1.7 on 2025-09-07 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_gameleague_last_standings_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='standingsbatch',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='season.league'),
        ),
    ]
