# Generated by Django 5.1.7 on 2025-09-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0003_standingsbatch_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizepayout',
            name='entry_fee_per_player',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, prize = entry_fee_per_player × number of players', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='prizepayout',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Fixed payout if entry_fee_per_player is not used', max_digits=9),
        ),
    ]
