# Generated by Django 5.1.7 on 2025-09-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0004_prizepayout_entry_fee_per_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizepayout',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed payout if entry_fee_per_player is not used', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='prizepayout',
            name='rank',
            field=models.PositiveIntegerField(blank=True, help_text='Optional if entry_fee_per_player is used.', null=True),
        ),
    ]
