# Generated by Django 5.1.7 on 2025-09-16 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0005_alter_prizepayout_amount_alter_prizepayout_rank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prizepayout',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_prize', to=settings.AUTH_USER_MODEL),
        ),
    ]
