# Generated by Django 5.1.7 on 2025-09-20 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0006_prizepayout_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizepayout',
            name='awarded_for_month',
            field=models.DateField(blank=True, help_text='Last day of the month this payout applies to (for monthly prizes)', null=True),
        ),
        migrations.AlterField(
            model_name='prizepayout',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='season.playergame'),
        ),
    ]
