# Generated by Django 5.1.7 on 2025-09-24 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0007_prizepayout_awarded_for_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizepayout',
            name='winning_pick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_payouts', to='season.playerpick'),
        ),
    ]
