# Generated by Django 5.1.7 on 2025-09-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0008_prizepayout_winning_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizepayout',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
