# Generated by Django 5.1.7 on 2025-09-28 16:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0009_prizepayout_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizepayout',
            name='points',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9),
        ),
    ]
