# Generated by Django 5.1.7 on 2025-10-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0010_alter_prizepayout_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='standingsbatch',
            name='is_month_end',
            field=models.BooleanField(default=False),
        ),
    ]
