# Generated by Django 5.1.7 on 2026-05-23 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0011_standingsbatch_is_month_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizepayout',
            name='entry_fee_per_player',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, prize = entry_fee_per_player  number of players', max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='SeasonDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('straight', 'Straight (same order each round)'), ('snake', 'Snake (reverse every other round)')], default='straight', max_length=10)),
                ('phase', models.CharField(choices=[('win_lose', 'Win & Lose Picks'), ('handicap', 'Handicap Picks'), ('complete', 'Draft Complete')], default='win_lose', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='season.game')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftSlotSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_type', models.CharField(choices=[('win', 'Win Team'), ('handicap', 'Handicap Team'), ('lose', 'Lose Team')], max_length=10)),
                ('pick_number', models.PositiveIntegerField()),
                ('round_number', models.PositiveSmallIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('skipped', models.BooleanField(default=False)),
                ('game_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_slots', to='season.gameleague')),
                ('player_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_slots', to='season.playergame')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='season.seasondraft')),
            ],
            options={
                'ordering': ['pick_number'],
                'unique_together': {('draft', 'pick_number')},
            },
        ),
        migrations.CreateModel(
            name='DraftOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('player_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_orders', to='season.playergame')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='season.seasondraft')),
            ],
            options={
                'ordering': ['draft', 'position'],
                'unique_together': {('draft', 'player_game'), ('draft', 'position')},
            },
        ),
    ]
