# Generated by Django 5.1.7 on 2026-05-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0012_alter_prizepayout_entry_fee_per_player_seasondraft_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='draftslotseason',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='draftslotseason',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='draftslotseason',
            name='game_league',
        ),
        migrations.RemoveField(
            model_name='draftslotseason',
            name='player_game',
        ),
        migrations.RemoveField(
            model_name='seasondraft',
            name='game',
        ),
        migrations.AddField(
            model_name='prizepool',
            name='sub_category',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='DraftOrder',
        ),
        migrations.DeleteModel(
            name='DraftSlotSeason',
        ),
        migrations.DeleteModel(
            name='SeasonDraft',
        ),
    ]
