# Generated by Django 5.1.7 on 2026-08-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0013_alter_draftslotseason_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='draft_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='draft_method',
            field=models.CharField(choices=[('straight', 'Straight'), ('snake', 'Snake')], default='straight', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
