# Generated by Django 5.1.7 on 2026-08-09 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0015_seasondraft_draftslotseason_draftorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftslotseason',
            name='round_number',
        ),
        migrations.AddField(
            model_name='draftslotseason',
            name='phase',
            field=models.CharField(choices=[('win_lose', 'Win/Lose'), ('handicap', 'Handicap')], default='win_lose', max_length=10),
        ),
        migrations.AlterField(
            model_name='draftslotseason',
            name='game_league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_slots', to='season.gameleague'),
        ),
        migrations.AlterField(
            model_name='draftslotseason',
            name='pick_type',
            field=models.CharField(blank=True, choices=[('win', 'Win Team'), ('handicap', 'Handicap Team'), ('lose', 'Lose Team')], default='', max_length=10),
        ),
    ]
