# Generated by Django 5.1.7 on 2025-07-31 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_alter_usergroup_access_code_alter_usergroup_members'),
        ('score_predict', '0003_prediction_alternate_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LastManStandingGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('league', models.CharField(choices=[('EPL', 'Premier League'), ('CH', 'Championship'), ('L1', 'League One'), ('L2', 'League Two')], max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_games', to='groups.usergroup')),
            ],
        ),
        migrations.CreateModel(
            name='LMSEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive', models.BooleanField(default=True)),
                ('eliminated_round', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='lms.lastmanstandinggame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='LMSRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='lms.lastmanstandinggame')),
            ],
        ),
        migrations.CreateModel(
            name='LMSPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('result', models.CharField(choices=[('PENDING', 'Pending'), ('WIN', 'Win'), ('LOSE', 'Lose'), ('DRAW', 'Draw')], default='PENDING', max_length=10)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='lms.lmsentry')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score_predict.fixture')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='lms.lmsround')),
            ],
            options={
                'unique_together': {('entry', 'round')},
            },
        ),
    ]
