# Generated by Django 5.1.7 on 2025-07-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_usergroup_access_code_alter_usergroup_members'),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LastManStandingGame',
            new_name='LMSGame',
        ),
    ]
