# Generated by Django 5.1.7 on 2025-08-04 18:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_rename_lastmanstandinggame_lmsgame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lmsgame',
            name='name',
        ),
        migrations.AddField(
            model_name='lmsgame',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6),
        ),
    ]
