# Generated by Django 5.1.7 on 2025-08-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_lmsgame_winner'),
        ('score_predict', '0006_alter_gameentry_alt_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsround',
            name='fixtures',
            field=models.ManyToManyField(blank=True, related_name='lms_rounds', to='score_predict.fixture'),
        ),
    ]
