# Generated by Django 5.1.7 on 2025-08-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_lmsround_fixtures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmsgame',
            name='league',
            field=models.CharField(choices=[('EPL', 'Premier League'), ('ECH', 'Championship'), ('EL1', 'League One'), ('EL2', 'League Two')], max_length=3),
        ),
    ]
