# Generated by Django 5.1.7 on 2025-11-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_lmsgame_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsentry',
            name='deadline_mode',
            field=models.CharField(choices=[('first_game', 'First game kickoff'), ('extended', "Extended (up to your team's kickoff)")], default='first_game', max_length=20),
        ),
        migrations.AddField(
            model_name='lmsentry',
            name='no_pick_rule',
            field=models.CharField(choices=[('elimination', 'Elimination'), ('lowest_team', 'Assign lowest-ranked team')], default='elimination', max_length=20),
        ),
    ]
