# Generated by Django 5.1.7 on 2025-12-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_remove_lmsentry_deadline_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmsgame',
            name='deadline_mode',
            field=models.CharField(choices=[('first_game', 'First game kickoff'), ('extended', 'Extended (pick team before they kickoff)')], default='first_game', max_length=20),
        ),
        migrations.AlterField(
            model_name='lmsgame',
            name='no_pick_rule',
            field=models.CharField(choices=[('elimination', 'Elimination'), ('random_team', 'Assigned random away team')], default='elimination', max_length=20),
        ),
    ]
