# Generated by Django 5.1.7 on 2025-12-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_alter_lmsgame_deadline_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsround',
            name='auto_pick_team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
