# Generated by Django 5.1.7 on 2025-12-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_lmsround_auto_pick_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsround',
            name='auto_pick_team1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lmsround',
            name='auto_pick_team2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lmsround',
            name='auto_pick_team3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
