# Generated by Django 5.1.7 on 2025-12-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_lmsround_auto_pick_team1_lmsround_auto_pick_team2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmspick',
            name='auto_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
