# Generated by Django 5.1.7 on 2025-07-20 14:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_alter_usergroup_access_code_alter_usergroup_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('game_type', models.CharField(choices=[('weekend', 'Weekend'), ('midweek', 'Midweek')], max_length=10)),
                ('week', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GameEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_fee', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_instances', to='groups.usergroup')),
                ('players', models.ManyToManyField(related_name='score_games', through='score_predict.GameEntry', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='score_predict.gametemplate')),
            ],
            options={
                'unique_together': {('template', 'group')},
            },
        ),
        migrations.AddField(
            model_name='gameentry',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score_predict.gameinstance'),
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField(choices=[(17, 'Premier League'), (18, 'Championship'), (24, 'League One'), (25, 'League Two')])),
                ('league_short_name', models.CharField(choices=[('EPL', 'EPL'), ('ECH', 'ECH'), ('EL1', 'EL1'), ('EL2', 'EL2')], max_length=3)),
                ('fixture_id', models.BigIntegerField(unique=True)),
                ('date', models.DateTimeField()),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_colour', models.CharField(blank=True, max_length=7, null=True)),
                ('home_text', models.CharField(blank=True, max_length=7, null=True)),
                ('away_colour', models.CharField(blank=True, max_length=7, null=True)),
                ('away_text', models.CharField(blank=True, max_length=7, null=True)),
                ('final_result_only', models.BooleanField(blank=True, default=False, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('status_description', models.CharField(blank=True, max_length=50, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('H', 'Home Win'), ('D', 'Draw'), ('A', 'Away Win'), ('N', 'Not Played')], default='N', max_length=1, null=True)),
                ('gametemplate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='score_predict.gametemplate')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='gameentry',
            unique_together={('game', 'player')},
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('predicted_home_score', models.IntegerField()),
                ('predicted_away_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture', to='score_predict.fixture')),
                ('game_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='score_predict.gameinstance')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('player', 'fixture')},
            },
        ),
    ]
