# Generated by Django 5.1.7 on 2025-03-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField(choices=[('39', 'Premier League'), ('40', 'Championship'), ('41', 'League One'), ('42', 'League Two')])),
                ('league_short_name', models.CharField(choices=[('PL', 'PL'), ('CH', 'CH'), ('L1', 'L1'), ('L2', 'L2')], max_length=2)),
                ('fixture_id', models.BigIntegerField(unique=True)),
                ('date', models.DateTimeField()),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('H', 'Home Win'), ('D', 'Draw'), ('A', 'Away Win'), (None, 'Not Played')], max_length=1, null=True)),
            ],
        ),
    ]
