# Generated by Django 5.1.7 on 2025-07-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='away_colour',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_text',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='final_result_only',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_colour',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_text',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='status_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
