# Generated by Django 5.1.7 on 2025-07-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_predict', '0002_fixture_away_colour_fixture_away_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='league_short_name',
            field=models.CharField(choices=[('PL', 'PL'), ('CH', 'CH'), ('L1', 'L1'), ('L2', 'L2')], max_length=3),
        ),
    ]
