# Generated by Django 5.1.7 on 2025-07-19 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_usergroup_access_code_alter_usergroup_members'),
        ('score_predict', '0003_alter_fixture_league_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fixtures',
            field=models.ManyToManyField(related_name='included_in_games', to='score_predict.fixture'),
        ),
        migrations.AddField(
            model_name='game',
            name='group',
            field=models.ForeignKey(default='Weekend', on_delete=django.db.models.deletion.CASCADE, related_name='score_games', to='groups.usergroup'),
            preserve_default=False,
        ),
    ]
