# Generated by Django 5.1.7 on 2025-08-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_predict', '0003_prediction_alternate_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameentry',
            name='alt_score',
            field=models.IntegerField(default=0),
        ),
    ]
