# Generated by Django 5.1.7 on 2025-08-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_predict', '0005_alter_gameentry_alt_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameentry',
            name='alt_score',
            field=models.IntegerField(default=0),
        ),
    ]
