# Generated by Django 5.1.7 on 2025-08-16 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_predict', '0007_alter_prediction_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinstance',
            name='winner',
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='won_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
