# Generated by Django 5.1.7 on 2025-10-11 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_predict', '0008_remove_gameinstance_winner_gameinstance_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
