# Generated by Django 5.1.7 on 2025-10-11 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_predict', '0009_fixture_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fixture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
