# Generated by Django 5.1.7 on 2025-08-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fixtures_results_check', models.DateTimeField(blank=True, null=True)),
                ('last_tables_check', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
