# Generated by Django 5.1.7 on 2025-10-11 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0011_standingsbatch_is_month_end'),
        ('updater', '0002_rename_last_fixtures_results_check_updatetracker_last_fixtures_check_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueUpdateTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fixtures_check', models.DateTimeField(blank=True, null=True)),
                ('last_results_check', models.DateTimeField(blank=True, null=True)),
                ('last_tables_check', models.DateTimeField(blank=True, null=True)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='season.league')),
            ],
        ),
    ]
