# Generated by Django 5.1.7 on 2026-05-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0003_leagueupdatetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatetracker',
            name='last_golf_events_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
