# Generated by Django 5.1.7 on 2026-05-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0004_updatetracker_last_golf_events_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatetracker',
            name='last_golf_rankings_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
